# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANT_API_VERSION         = "2"
ENV['VAGRANT_NO_PARALLEL']  = 'yes'

VAGRANT_BOX         = "generic/ubuntu2204"
VAGRANT_BOX_VERSION = "4.2.10"
CPUS_WORKER_NODE    = 2
MEMORY_WORKER_NODE  = 4096
WORKER_NODES_COUNT  = 3
NETWORK_PREFIX      = "172.16.16"


Vagrant.configure(VAGRANT_API_VERSION) do |config|

  config.vm.box               = VAGRANT_BOX
  config.vm.box_check_update  = false
  config.vm.box_version       = VAGRANT_BOX_VERSION
  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Worker Nodes
  (1..WORKER_NODES_COUNT).each do |i|

    config.vm.define "rke-node#{i}" do |node|

      node.vm.hostname = "rke-node#{i}.example.com"
      node.vm.network "private_network", ip: "#{NETWORK_PREFIX}.21#{i}"

      node.vm.provider :virtualbox do |v|
        v.name    = "rke-node#{i}"
        v.memory  = MEMORY_WORKER_NODE
        v.cpus    = CPUS_WORKER_NODE
      end

      node.vm.provider :libvirt do |v|
        v.memory  = MEMORY_WORKER_NODE
        v.nested  = true
        v.cpus    = CPUS_WORKER_NODE
      end

    end

  end

end